### ISSUE TITLE
__init__ missing

### ISSUE THREAD

**Issue by vicentecarro** [AARG-FAN/Image-Raster-for-ComfyUI#1]
It seems the customnode is missing a __init__.py file

```
Traceback (most recent call last):
  File "/media/user/Samsung870VQO1TB/comfyui/ComfyUI/nodes.py", line 1879, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1128, in get_code
  File "<frozen importlib._bootstrap_external>", line 1186, in get_data
FileNotFoundError: [Errno 2] No such file or directory: '/media/user/Samsung870VQO1TB/comfyui/ComfyUI/custom_nodes/Image-vector-for-ComfyUI/__init__.py'
```

I install it following the repo instructions, not the comfyui manager, as I tried that before and didn't work.

**Comment by AARG-FAN** [comment]
already added, please check the update
